name: SpaceWars
main: it.tristana.spacewars.Main
api-version: 1.19
author: Massimiliano Micol
softdepend: [PlaceholderAPI]
depend: [TristanaCommons, NBTAPI]
version: 1.1.0
commands:
  sw:
    description: Main command
    usage: /sw help
    permission: spacewars.player
    default: true